- name: Query VMs on Proxmox VE
  hosts: hosts
  connection: local
  gather_facts: false
  vars:
    api_host: "{{ ansible_host }}"
    api_user: "{{ proxmox_user }}"
    api_token_id: "{{ proxmox_token_id }}"
    api_token_secret: "{{ lookup('env', 'proxmox_token_secret') }}"
  pre_tasks:
    - name: Install Python library locally inside the AWX runner container
      ansible.builtin.pip:
        name: 
         - proxmoxer
         - requests
         - ansible
        extra_args: --user
      delegate_to: localhost
      run_once: true

  tasks:
  - name: Get VM inventory
    community.proxmox.proxmox_vm_info:
      api_user: "{{ api_user }}"
      api_host: "{{ api_host }}"
      api_token_id: "{{ api_token_id }}"
      api_token_secret: "{{ api_token_secret }}"
      validate_certs: false
    register: proxmox_inventory

  - name: Display Proxmox inventory list
    ansible.builtin.debug:
      var: proxmox_inventory
