- name: Query VMs on Proxmox VE
  hosts: localhost
  gather_facts: false
  vars:
    api_host: "{{ proxmox_host }}"
    api_user: "{{ proxmox_user }}"
    api_token_id: "{{ proxmox_token_id }}"
    api_token_secret: "{{ proxmox_token_secret }}"
  tasks:
  - name: Get VM inventory
    group/community.proxmox.proxmox_vm_info:
      api_user: "{{ api_user }}"
      api_host: "{{ api_host }}"
      api_token_id: "{{ api_token_id }}"
      api_token_secret: "{{ api_token_secret }}"
    register: proxmox_inventory

  - name: Display Proxmox inventory list
    ansible.builtin.debug:
      var: proxmox_inventory
