---
- hosts: all
  gather_facts: true
  tasks:
    - name: Print the OS distribution
      ansible.builtin.debug:
        msg: "Target system is {{ ansible_facts['distribution'] }} version {{ ansible_facts['distribution_version'] }}"


    - name: Run Proxmox Checklist Script.
      ansible.builtin.command: pve7to8 --full 
      register: checklist_output

    - name: Print the Proxmox Checklist output. 
      ansible.builtin.debug:
        var: checklist_output.stdout

# TO DO: 
# Shutdown VMs and Containers
# Backup VMs and Containers.
# Dist Upgrade
# Update Debian Base Repositories to Bookworm
# Add the Proxmox VE 8 Package Repository
# Refresh Package Index: apt Update
# Upgrade the system to Debian Bookworm and Proxmox VE 8.0
#   apt update
#   apt dist-upgrade
# Check Result & Reboot Into Updated Kernel
#   Checklist
#.  Reboot.

